<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-04-30 at 18:12:58.
 */
class SaleskingHelperTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var SaleskingHelper
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers SaleskingHelper::pluralize
     */
    public function testPluralize()
    {
        $this->assertEquals("clients",SaleskingHelper::pluralize("client"));
        $this->assertEquals("companies",SaleskingHelper::pluralize("company"));

    }

    /**
     * @covers SaleskingHelper::loadSchema
     */
    public function testLoadSchema()
    {
        // not existing schema cant be called
        $thrown = false;
        try {
            SaleskingHelper::loadSchema("notexisting");
        }
        catch (SaleskingException $e)
        {
            if($e->getCode() == "SCHEMA_NOTFOUND" AND $e->getMessage() == "Could not find schema file."){
                $thrown = true;
            }
        }
        $this->assertTrue($thrown);

        $this->assertInstanceOf("stdClass",SaleskingHelper::loadSchema("client"));
    }
}
